version: '3.7'

services:
  test:
    image: stealthy-backend:test-latest
    build:
      context: .
      target: test_application
    network_mode: bridge

  check-code:
    image: stealthy-backend:code-check-latest
    build:
      context: .
      target: check_code_app
    network_mode: bridge
    volumes:
      - ./src:/app
