version: '3.7'

services:
  mongo-db:
    image: mongo:7.0.2-jammy
    ports:
      - "27017:27017"
    env_file:
      - ".env"
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://backend:password@mongo-db:27017/stealthy-backend?directConnection=true&authSource=admin"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
    depends_on:
      - mongo-db
