version: '3.7'

services:
  mongo-db:
    image: mongo:7.0.2-jammy
    ports:
      - "27017:27017"
    env_file:
      - ".env"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: "backend"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "password"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: "mongo-db"
    depends_on:
      - mongo-db
