name: Check commit code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Build test containers
      run: docker-compose -f docker-compose-test.yml build

    - name: Run tests
      run: docker-compose -f docker-compose-test.yml --exit-code-from test up

    - name: Remove test containers
      run: docker-compose -f docker-compose-test.yml down
