name: Check commit code

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose-test.yml"
